### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by DaniPopes** [paradigmxyz/solar#1]
- [ ] Frontend
  - [x] Input
    - [x] CLI arguments
    - [x] Unstable CLI arguments (`-Z`)
    - [ ] Standard JSON
  - [ ] Stable vs unstable/nightly separation (?)
  - [x] Config
    - [x] CLI arguments
    - [ ] TOML file (?)
  - [x] Diagnostics
    - [x] Builder
    - [x] Human-readable emitter ([`annotate-snippets`](https://crates.io/crates/annotate-snippets))
    - [x] JSON emitter
  - [x] File loading/resolution
  - [x] Lexing
    - [x] Low-level cursor
    - [x] Glued (combined) tokens (e.g. `Plus, Eq` -> `BinOpEq(Plus)`)
    - [x] Interned strings (`Symbol`)
  - [x] AST #26
    - [x] Data structures
    - [x] ~~IDs (?)~~
    - [x] Visitors
    - [ ] Pretty printer #27
  - [x] Parsing #26
    - [x] Items (source unit and contract elements)
    - [x] Pragma versions
    - [x] Statements
    - [x] Expressions
    - [x] Literals
    - [x] Types
      - [x] ~~`[u]fixedMxN`~~
    - [x] Yul
  - [x] AST validation #29
  - [x] HIR
    - [x] AST to HIR
    - [ ] Yul to HIR https://github.com/paradigmxyz/solar/issues/415
    - [x] Symbol resolution
    - [x] Generate state variable getters #52
    - [ ] Builder https://github.com/ithacaxyz/solar/issues/64
    - [ ] Recursive visitors https://github.com/ithacaxyz/solar/issues/63
    - [ ] Pretty printer https://github.com/ithacaxyz/solar/issues/86
  - [x] Type system
    - [x] HIR to Ty
    - [x] Array length evaluation
  - [ ] Type checking (#615)
    - [ ] Better "Member not found or not visible after argument-dependent lookup" error message 
  - [x] Emit ABI
    - [ ] Include *referenced* events and errors, alongside the defined ones https://github.com/paradigmxyz/solar/issues/305
  - [ ] Misc checks
    - [x] [ContractLevelChecker](https://github.com/DaniPopes/solidity/blob/de1a017ccb935d149ed6bcbdb730d89883f8ce02/libsolidity/analysis/ContractLevelChecker.cpp) https://github.com/paradigmxyz/solar/issues/303
    - [ ] view/pure checker
    - [ ] static analysis + lint infrastructure
  - [ ] Control-flow graph (CFG) generation
    - [ ] Unused/unreachable declarations
- [ ] Middle-end / optimizer
  - Third-party:
    - [Venom](https://github.com/vyperlang/vyper/tree/master/vyper/venom)
    - [Sonatina](https://github.com/fe-lang/sonatina/)
    - [solx](https://github.com/matter-labs/solx)
  - [ ] Local middle-end IR
    - In-tree intermediate IR to run optimizations locally before codegen
  - [ ] Basic optimizations
  - [ ] Solidity-specific optimizations
    - ...?
- [ ] Backend / codegen
  - [ ] EVM, legacy
  - [ ] EVM, EOF v1

---

- [ ] Tests
  - [x] Solc
  - [x] UI
  - [ ] Codegen with [LLVM FileCheck](https://llvm.org/docs/CommandGuide/FileCheck.html)
  - [ ] Run
    - [ ] bytecode with revm
    - [ ] IR with interpreter
